# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=1000)),
                ('owner', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
