# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180215_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('article', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
