# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180210_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
